### ISSUE TITLE
Latest version Error Opening File

### ISSUE THREAD

**Issue by Dusky** [IAmPattycakes/ChatRat#14]
Previous version works just fine. 
latest version throws "error opening file: open : The system cannot find the file specified."

**Comment by IAmPattycakes** [comment]
Yeah I screwed up something in the logger. Editing without a run environment or IDE will getcha sometimes I guess. I'll get to debugging it tonight.

**Comment by IAmPattycakes** [comment]
Okay yeah that issue was actually because I was dumb and didn't have the code and the .json file tags lined up. The "logFIle" tag should be renamed to "logName" if you already have your settings done. And pull latest once it merges in a minute. I promise I actually tested it this time.
